### ISSUE TITLE
NPE in XmlPublisherDataRouter when publishing delete event type

### ISSUE THREAD

**Issue by dmitz** [JumpMind/symmetric-ds#33]
It occurs when using XmlPublisherDataRouter for XML publishing.
This error has been fixed in [this issue](http://www.symmetricds.org/issues/view.php?id=2265), but only for XmlPublisherDatabaseWriterFilter

`ERROR | engine-name-job-18 | Failed to route and batch data on 'jms' channel
java.lang.NullPointerException
	at org.jumpmind.symmetric.integrate.AbstractXmlPublisherExtensionPoint.toXmlGroupId(AbstractXmlPublisherExtensionPoint.java:380)
	at org.jumpmind.symmetric.integrate.AbstractXmlPublisherExtensionPoint.getXmlFromCache(AbstractXmlPublisherExtensionPoint.java:342)
	at org.jumpmind.symmetric.integrate.XmlPublisherDataRouter.routeToNodes(XmlPublisherDataRouter.java:65)
	at org.jumpmind.symmetric.service.impl.RouterService.routeData(RouterService.java:756)
	at org.jumpmind.symmetric.service.impl.RouterService.selectDataAndRoute(RouterService.java:674)
	at org.jumpmind.symmetric.service.impl.RouterService.routeDataForChannel(RouterService.java:476)
	at org.jumpmind.symmetric.service.impl.RouterService.routeDataForEachChannel(RouterService.java:336)
	at org.jumpmind.symmetric.service.impl.RouterService.routeData(RouterService.java:184)
	at org.jumpmind.symmetric.job.RouterJob.doJob(RouterJob.java:40)
	at org.jumpmind.symmetric.job.AbstractJob.invoke(AbstractJob.java:180)
	at org.jumpmind.symmetric.job.AbstractJob.run(AbstractJob.java:224)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by dmitz** [comment]
#34 This PR fixed this issue

**Comment by dmitz** [comment]
Closed, because PR was merged
